baseURL = "https://xn--dtour-bsa.studio/"
defaultContentLanguage = "fr"
languageCode = "fr-FR"
title = "détour.studio"

theme = "detour"
sectionPagesMenu = "works"
buildFuture = true
rssLimit = 10
cleanDestinationDir = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  description = "Je donne du sens à des services numériques libres et conviviaux. Je privilégie des projets qui font progresser la biodiversité, ou les connaissances."
  pronouns = "il / lui"

[related]
  includeNewer = true
  toLower = true
[[related.indices]]
  name = "keywords"
  weight = 100
[[related.indices]]
  name = "for"
  weight = 50

[outputFormats]
  [outputFormats.opml]
    basename = "collection"
    mediaType = "application/xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
      attribute = true

[menu]
  [[menu.main]]
    name = "Projets"
    url = "/#développement-web"
    weight = 90
    params = { icon = "love" }

[taxonomies]
  category = "categories"
  stack = "stack"
