name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy w/ rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          path: public/
          remote_path: /home/oncletom/www_detour_studio
          switches: -avzr --delete --exclude node_modules --exclude '.git*'
          remote_host: ssh-oncletom.alwaysdata.net
          remote_user: oncletom
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
